CREATE OR REPLACE
    ALGORITHM = UNDEFINED 
    DEFINER = `spb`@`%` 
    SQL SECURITY DEFINER
VIEW `cv`.`vwTableInstances` AS
 
 SELECT -- `TABLES`.`TABLE_CATALOG`,
    -- `TABLES`.`TABLE_SCHEMA`,
    `TABLES`.`TABLE_NAME`,
    `TABLES`.`TABLE_TYPE`,
    -- `TABLES`.`ENGINE`,
    `TABLES`.`TABLE_ROWS`,
    `TABLES`.`VERSION`,
    -- `TABLES`.`ROW_FORMAT`,
    
    -- `TABLES`.`AVG_ROW_LENGTH`,
    -- `TABLES`.`DATA_LENGTH`,
    -- `TABLES`.`MAX_DATA_LENGTH`,
    -- `TABLES`.`INDEX_LENGTH`,
   --  `TABLES`.`DATA_FREE`,
     `TABLES`.`AUTO_INCREMENT`,
     `TABLES`.`CREATE_TIME` `SYS_CREATE_TIME`,
    `TABLES`.`UPDATE_TIME` `SYS_UPDATE_TIME`,
--     `TABLES`.`CHECK_TIME`,
--     `TABLES`.`TABLE_COLLATION`,
--     `TABLES`.`CHECKSUM`,
--     `TABLES`.`CREATE_OPTIONS`,
    `TABLES`.`TABLE_COMMENT`
FROM `information_schema`.`TABLES`
where `TABLES`.`TABLE_SCHEMA` = 'cv'
ORDER BY `TABLE_TYPE`,`TABLE_NAME`;
   
    
    
     
