CREATE OR REPLACE VIEW `cv`.`vwTableMeta`

AS

SELECT 
`T`.`TABLE_NAME` ,
(CASE !ISNULL(`T`.`AUTO_INCREMENT`) WHEN TRUE THEN `T`.`AUTO_INCREMENT` ELSE 'NOT INCREMENTED!' END)   `INSERT_ID`,
`T`.`TABLE_ROWS` `ROWCOUNT`,
`C`.`CONSTRAINT_TYPE` `CONSTRAINT`,
`C`.`CONSTRAINT_NAME`



FROM 

(SELECT 

`TABLE_NAME`,
`TABLE_ROWS`,
`AUTO_INCREMENT`

 FROM `information_schema`.`TABLES`
WHERE `TABLE_SCHEMA` = 'cv' AND `TABLE_TYPE` = 'BASE TABLE') AS `T`

LEFT JOIN 
(SELECT  `TABLE_CONSTRAINTS`.`TABLE_NAME`,
    `TABLE_CONSTRAINTS`.`CONSTRAINT_TYPE`,
     `TABLE_CONSTRAINTS`.`CONSTRAINT_NAME`
FROM `information_schema`.`TABLE_CONSTRAINTS`) AS `C`

ON `T`.`TABLE_NAME` = `C`.`TABLE_NAME`

ORDER BY (SELECT CASE (`C`.`CONSTRAINT_TYPE`) WHEN 'PRIMARY KEY' THEN '1' WHEN 'FOREIGN KEY' THEN '2' WHEN 'UNIQUE' THEN '3' ELSE '4' END),
`T`.`TABLE_NAME`;






